import { responseVerification } from "@/lib/utils";
import { sort } from "@/types/types";

const API_KEY = process.env.NEXT_PUBLIC_TMDB_API_KEY;

const options = {
  headers: {
    Authorization: `Bearer ${API_KEY}`,
    accept: "application/json",
  },
};

export async function obtainCountriesConfigurations() {
  const url =
    "https://api.themoviedb.org/3/configuration/countries?language=fr-FR";
  try {
    const response = await fetch(url, options);
    await responseVerification(response, url);
    const data = await response.json();

    return data;
  } catch (error) {
    console.error(error);
    throw error;
  }
}

export async function obtainLanguagesConfigurations() {
  const url = "https://api.themoviedb.org/3/configuration/languages";
  try {
    const response = await fetch(url, options);
    await responseVerification(response, url);
    const data = await response.json();

    return data;
  } catch (error) {
    console.error(error);
    throw error;
  }
}

export async function obtainGenres(type: string) {
  const url = `https://api.themoviedb.org/3/genre/${type}/list?language=fr`;
  try {
    const response = await fetch(url, options);
    await responseVerification(response, url);
    const data = await response.json();

    return data.genres;
  } catch (error) {
    console.error(error);
    throw error;
  }
}

export const movies_sort_by: sort[] = [
  {
    name: "Popularité +/-",
    value: "popularity.desc",
  },
  {
    name: "Popularité -/+",
    value: "popularity.asc",
  },
  {
    name: "Revenue +/-",
    value: "revenue.desc",
  },
  {
    name: "Revenue -/+",
    value: "revenue.asc",
  },
  {
    name: "Date de sortie +/-",
    value: "primary_release_date.desc",
  },
  {
    name: "Date de sortie -/+",
    value: "primary_release_date.asc",
  },
  {
    name: "Evaluation +/-",
    value: "vote_average.desc",
  },
  {
    name: "Evaluation -/+",
    value: "vote_average.asc",
  },
];

export const tv_sort_by: sort[] = [
  {
    name: "Popularité +/-",
    value: "popularity.desc",
  },
  {
    name: "Popularité -/+",
    value: "popularity.asc",
  },
  {
    name: "Date de premiere diffusion +/-",
    value: "first_air_date.desc",
  },
  {
    name: "Date de premiere diffusion -/+",
    value: "first_air_date.asc",
  },
  {
    name: "Evaluation +/-",
    value: "vote_average.desc",
  },
  {
    name: "Evaluation -/+",
    value: "vote_average.asc",
  },
];

export const botUserAgents = [
  "Googlebot",
  "Googlebot-Mobile",
  "Googlebot-Image",
  "Googlebot-News",
  "Googlebot-Video",
  "AdsBot-Google",
  "AdsBot-Google-Mobile",
  "Feedfetcher-Google",
  "Mediapartners-Google",
  "Mediapartners Googlebot",
  "APIs-Google",
  "Google-InspectionTool",
  "Storebot-Google",
  "GoogleOther",
  "bingbot",
  "Slurp",
  "wWget",
  "LinkedInBot",
  "Python-urllib",
  "python-requests",
  "aiohttp",
  "httpx",
  "libwww-perl",
  "httpunit",
  "nutch",
  "Go-http-client",
  "phpcrawl",
  "msnbot",
  "jyxobot",
  "FAST-WebCrawler",
  "FAST Enterprise Crawler",
  "BIGLOTRON",
  "Teoma",
  "convera",
  "seekbot",
  "Gigabot",
  "Gigablast",
  "exabot",
  "ia_archiver",
  "GingerCrawler",
  "webmon",
  "HTTrack",
  "gruborg",
  "UsineNouvelleCrawler",
  "antibot",
  "netresearchserver",
  "speedy",
  "fluffy",
  "findlink",
  "msrbot",
  "panscient",
  "yacybot",
  "AISearchBot",
  "ips-agent",
  "tagoobot",
  "MJ12bot",
  "woriobot",
  "yanga",
  "buzzbot",
  "mlbot",
  "yandexcombots",
  "purebot",
  "Linguee Bot",
  "CyberPatrol",
  "voilabot",
  "Baiduspider",
  "citeseerxbot",
  "spbot",
  "twengabot",
  "postrank",
  "Turnitin",
  "scribdbot",
  "page2rss",
  "sitebot",
  "linkdex",
  "Adidxbot",
  "ezooms",
  "dotbot",
  "MailRU_Bot",
  "discobot",
  "heritrix",
  "findthatfile",
  "europarchiveorg",
  "NerdByNatureBot",
  "sistrix crawler",
  "AhrefsBotSiteAudit",
  "fuelbot",
  "CrunchBot",
  "IndeedBot",
  "mappydata",
  "woobot",
  "ZoominfoBot",
  "PrivacyAwareBot",
  "Multiviewbot",
  "SWIMGBot",
  "Grobbot",
  "eright",
  "Apercite",
  "semanticbot",
  "Aboundex",
  "domaincrawler",
  "wbsearchbot",
  "summify",
  "CCBot",
  "edisterbot",
  "SeznamBot",
  "ec2linkfinder",
  "gslfbot",
  "aiHitBot",
  "intelium_bot",
  "facebookexternalhit",
  "Yeti",
  "RetrevoPageAnalyzer",
  "lb-spider",
  "Sogou",
  "lssbot",
  "careerbot",
  "wotbox",
  "wocbot",
  "ichiro",
  "DuckDuckBot",
  "lssrocketcrawler",
  "drupact",
  "webcompanycrawler",
  "acoonbot",
  "openindexspider",
  "gnam gnam spider",
  "web-archive-netcombot",
  "backlinkcrawler",
  "coccoc",
  "integromedb",
  "content crawler spider",
  "toplistbot",
  "it2media-domain-crawler",
  "ip-web-crawlercom",
  "siteexplorerinfo",
  "elisabot",
  "proximic",
  "changedetection",
  "arabot",
  "WeSEESearch",
  "niki-bot",
  "CrystalSemanticsBot",
  "rogerbot",
  "360Spider",
  "psbot",
  "InterfaxScanBot",
  "CC Metadata Scaper",
  "g00g1enet",
  "GrapeshotCrawler",
  "urlappendbot",
  "brainobot",
  "fr-crawler",
  "binlar",
  "SimpleCrawler",
  "Twitterbot",
  "cXensebot",
  "smtbot",
  "bnffr_bot",
  "A6-Indexer",
  "ADmantX",
  "Facebot",
  "OrangeBot",
  "memorybot",
  "AdvBot",
  "MegaIndex",
  "SemanticScholarBot",
  "ltx71",
  "nerdybot",
  "xovibot",
  "BUbiNG",
  "Qwantify",
  "archiveorg_bot",
  "Applebot",
  "TweetmemeBot",
  "crawler4j",
  "findxbot",
  "SeEmMrushBot",
  "yoozBot",
  "lipperhey",
  "YJ",
  "Domain Re-Animator Bot",
  "AddThis",
  "Screaming Frog SEO Spider",
  "MetaURI",
  "Scrapy",
  "LivelapbBot",
  "OpenHoseBot",
  "CapsuleChecker",
  "collectioninfegycom",
  "IstellaBot",
  "DeuSu",
  "betaBot",
  "Cliqzbot",
  "MojeekBot",
  "netEstate NE Crawler",
  "SafeSearch microdata crawler",
  "Gluten Free Crawler",
  "Sonic",
  "Sysomos",
  "Trove",
  "deadlinkchecker",
  "Slack-ImgProxy",
  "Embedly",
  "RankActiveLinkBot",
  "iskanie",
  "SafeDNSBot",
  "SkypeUriPreview",
  "Veoozbot",
  "Slackbot",
  "redditbot",
  "datagnionbot",
  "Google-Adwords-Instant",
  "adbeat_bot",
  "WhatsApp",
  "contxbot",
  "pinterestcombot",
  "electricmonk",
  "GarlikCrawler",
  "BingPreview",
  "vebidoobot",
  "FemtosearchBot",
  "Yahoo Link Preview",
  "MetaJobBot",
  "DomainStatsBot",
  "mindUpBot",
  "Daum",
  "Jugendschutzprogramm-Crawler",
  "Xenu Link Sleuth",
  "Pcore-HTTP",
  "moatbot",
  "KosmioBot",
  "pPingdom",
  "AppInsights",
  "PhantomJS",
  "Gowikibot",
  "PiplBot",
  "Discordbot",
  "TelegramBot",
  "Jetslide",
  "newsharecounts",
  "James BOT",
  "BarkrRowler",
  "TinEye",
  "SocialRankIOBot",
  "trendictionbot",
  "Ocarinabot",
  "epicbot",
  "Primalbot",
  "DuckDuckGo-Favicons-Bot",
  "GnowitNewsbot",
  "Leikibot",
  "LinkArchiver",
  "YaK",
  "PaperLiBot",
  "Digg Deeper",
  "dcrawl",
  "Snacktory",
  "AndersPinkBot",
  "Fyrebot",
  "EveryoneSocialBot",
  "Mediatoolkitbot",
  "Luminator-robots",
  "ExtLinksBot",
  "SurveyBot",
  "NING",
  "okhttp",
  "Nuzzel",
  "omgili",
  "PocketParser",
  "YisouSpider",
  "um-LN",
  "ToutiaoSpider",
  "MuckRack",
  "Jamies Spider",
  "AHC",
  "NetcraftSurveyAgent",
  "Laserlikebot",
  "Apache-HttpClient",
  "AppEngine-Google",
  "Jetty",
  "Upflow",
  "Thinklab",
  "Traackrcom",
  "Twurly",
  "Mastodon",
  "http_get",
  "DnyzBot",
  "botify",
  "007ac9 Crawler",
  "BehloolBot",
  "BrandVerity",
  "check_http",
  "BDCbot",
  "ZumBot",
  "EZID",
  "ICC-Crawler",
  "ArchiveBot",
  "LCC",
  "filterdbissnetcrawler",
  "BLP_bbot",
  "BomboraBot",
  "Buck",
  "Companybook-Crawler",
  "Genieo",
  "magpie-crawler",
  "MeltwaterNews",
  "Moreover",
  "newspaper",
  "ScoutJet",
  "sentry",
  "StorygizeBot",
  "UptimeRobot",
  "OutclicksBot",
  "seoscanners",
  "Hatena",
  "Google Web Preview",
  "MauiBot",
  "AlphaBot",
  "SBL-BOT",
  "IAS crawler",
  "adscanner",
  "Netvibes",
  "acapbot",
  "Baiduspider",
  "bitlybot",
  "blogmuraBot",
  "BotAraTurkacom",
  "bot-pgechlooecom",
  "BoxcarBot",
  "BTWebClient",
  "ContextAd Bot",
  "Digincore bot",
  "Disqus",
  "Feedly",
  "Fetch",
  "Fever",
  "Flamingo_SearchEngine",
  "FlipboardProxy",
  "g2reader-bot",
  "G2 Web Services",
  "imrbot",
  "K7MLWCBot",
  "Kemvibot",
  "Landau-Media-Spider",
  "linkapediabot",
  "vkShare",
  "Siteimprovecom",
  "BLEXBot",
  "DareBoost",
  "ZuperlistBot",
  "Miniflux",
  "Feedspot",
  "Diffbot",
  "SEOkicks",
  "tracemyfile",
  "Nimbostratus-Bot",
  "zgrab",
  "PR-CYRU",
  "AdsTxtCrawler",
  "Datafeedwatch",
  "Zabbix",
  "TangibleeBot",
  "google-xrawler",
  "axios",
  "Amazon CloudFront",
  "Pulsepoint",
  "CloudFlare-AlwaysOnline",
  "Google-Structured-Data-Testing-Tool",
  "WordupInfoSearch",
  "WebDataStats",
  "HttpUrlConnection",
  "Seekport Crawler",
  "ZoomBot",
  "VelenPublicWebCrawler",
  "MoodleBot",
  "jpg-newsbot",
  "outbrain",
  "W3C_Validator",
  "Validatornu",
  "W3C-checklink",
  "W3C-mobileOK",
  "W3C_I18n-Checker",
  "FeedValidator",
  "W3C_CSS_Validator",
  "W3C_Unicorn",
  "Google-PhysicalWeb",
  "Blackboard",
  "ICBot",
  "BazQux",
  "Twingly",
  "Rivva",
  "Experibot",
  "awesomecrawler",
  "Dataprovidercom",
  "GroupHigh",
  "theoldreadercom",
  "AnyEvent",
  "Uptimebotorg",
  "Nmap Scripting Engine",
  "2ipru",
  "Clickagy",
  "Caliperbot",
  "MBCrawler",
  "online-webceo-bot",
  "B2B Bot",
  "AddSearchBot",
  "Google Favicon",
  "HubSpot",
  "Chrome-Lighthouse",
  "HeadlessChrome",
  "CheckMarkNetwork",
  "wwwuptimecom",
  "Streamline3Bot",
  "serpstatbot",
  "MixnodeCache",
  "curl",
  "SimpleScraper",
  "RSSingBot",
  "Jooblebot",
  "fedoraplanet",
  "Friendica",
  "NextCloud",
  "Tiny Tiny RSS",
  "RegionStuttgartBot",
  "Bytespider",
  "Datanyze",
  "Google-Site-Verification",
  "TrendsmapResolver",
  "tweetedtimes",
  "NTENTbot",
  "Gwene",
  "SimplePie",
  "SearchAtlas",
  "Superfeedr",
  "feedbot",
  "UT-Dorkbot",
  "Amazonbot",
  "SerendeputyBot",
  "Eyeotabot",
  "officestorebot",
  "Neticle Crawler",
  "SurdotlyBot",
  "LinkisBot",
  "AwarioSmartBot",
  "AwarioRssBot",
  "RyteBot",
  "FreeWebMonitoring SiteChecker",
  "AspiegelBot",
  "NAVER Blog Rssbot",
  "zenback bot",
  "SentiBot",
  "Domains Project",
  "Pandalytics",
  "VKRobot",
  "bidswitchbot",
  "tigerbot",
  "NIXStatsbot",
  "Atom Feed Robot",
  "Ccurebot",
  "PagePeeker",
  "Vigil",
  "rssbot",
  "startmebot",
  "JobboerseBot",
  "seewithkids",
  "NINJA bot",
  "Cutbot",
  "BublupBot",
  "BrandONbot",
  "RidderBot",
  "Taboolabot",
  "Dubbotbot",
  "FindITAnswersbot",
  "infoobot",
  "Refindbot",
  "BlogTrafficdd Feed-Fetcher",
  "SeobilityBot",
  "Cincraw",
  "Dragonbot",
  "VoluumDSP-content-bot",
  "FreshRSS",
  "BitBot",
  "PHP-Curl-Class",
  "Google-Certificates-Bridge",
  "centurybot",
  "Viber",
  "eventures Investment Crawler",
  "evc-batch",
  "PetalBot",
  "virustotal",
  "PTST",
  "minicrawler",
  "Cookiebot",
  "trovitBot",
  "seostarco",
  "IonCrawl",
  "Uptime-Kuma",
  "SeekportBot",
  "FreshpingBot",
  "Feedbin",
  "CriteoBot",
  "Snap URL Preview Service",
  "Better Uptime Bot",
  "RuxitSynthetic",
  "Google-Read-Aloud",
  "ValveSteam",
  "OdklBot",
  "GPTBot",
  "YandexRenderResourcesBot",
  "LightspeedSystemsCrawler",
  "ev-crawler",
  "BitSightBot",
  "woorankreview",
  "Google-Safety",
  "AwarioBot",
  "DataForSeoBot",
  "Linespider",
  "WellKnownBot",
  "A Patent Crawler",
  "StractBot",
  "searchmarginalianu",
  "YouBot",
  "Nicecrawler",
  "Neevabot",
  "BrightEdge Crawler",
  "SiteCheckerBotCrawler",
  "TombaPublicWebCrawler",
  "CrawlyProjectCrawler",
  "KomodiaBot",
  "KStandBot",
  "CISPA Webcrawler",
  "MTRobot",
  "hyscoreio",
  "AlexandriaOrgBot",
  "2ip bot",
  "Yellowbrandprotectionbot",
  "SEOlizer",
  "vuhuvBot",
  "INETDEX-BOT",
  "Synapse",
  "t3versionsBot",
  "deepnoc",
  "Cocolyzebot",
  "hypestat",
  "ReverseEngineeringBot",
  "sempitech",
  "Iframely",
  "MetaInspector",
  "node-fetch",
  "lkxscan",
  "python-opengraph",
  "OpenGraphCheck",
  "developersgooglecomwebsnippet",
  "SenutoBot",
  "MaCoCu",
  "NewsBlur",
  "inoreader",
  "NetSystemsResearch",
  "PageThing",
  "WordPress",
];
